-- =============================================================================
-- Money Tracker — database schema
--
-- THIS FILE IS SAFE TO RUN AS MANY TIMES AS YOU LIKE.
--
-- It never deletes anything. There is no `drop table`, no `truncate` and no
-- `delete` anywhere below. Everything either creates what is missing or leaves
-- what already exists exactly as it is, rows included.
--
-- HOW TO USE IT
--   Supabase dashboard → SQL Editor → New query → paste this whole file → Run.
--   "Success. No rows returned" is the correct result; it is a schema script.
--
-- WHEN SOMETHING CHANGES
--   This same file gets updated and you paste the whole thing again. There is
--   only ever one database file in this project. New columns go in the "later
--   additions" section near the bottom of each table, which is written so that
--   re-running actually applies them to a table that already exists.
--
-- THE ONE RULE
--   If a change ever genuinely needs to remove or rewrite existing data, it
--   will not be quietly added to this file. You will be told first, and your
--   data exported to Excel before anything runs.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Helper: stamp updated_at on every write
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- =============================================================================
-- profiles — per-account settings that follow you across devices
-- =============================================================================
create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Columns are added separately from the table so that re-running this file on a
-- database that already has the table still picks up anything new. A column
-- inside `create table if not exists` would be skipped silently.
alter table public.profiles
  add column if not exists language text not null default 'en-GB',
  add column if not exists theme    text not null default 'neutral';

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();


-- =============================================================================
-- income_entries
--
--  * The primary key is a UUID generated by the app, not the database, so that
--    a future offline mode can create rows before they reach the server.
--  * `period` is the first day of the month a row belongs to (e.g. 2026-07-01).
--    Months themselves are never stored — they come from the calendar.
--  * There is no "received" boolean. The tick box is worked out in the app from
--    received_amount >= expected_amount, so the two can never disagree.
--  * deleted_at is a soft delete, kept for a future sync.
-- =============================================================================
create table if not exists public.income_entries (
  id      uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  period  date not null
);

alter table public.income_entries
  add column if not exists source          text not null default '',
  add column if not exists expected_date   date,
  add column if not exists expected_amount numeric(14, 2) not null default 0,
  add column if not exists received_amount numeric(14, 2) not null default 0,
  add column if not exists received_date   date,
  add column if not exists notes           text,
  add column if not exists sort_order      integer not null default 0,
  add column if not exists created_at      timestamptz not null default now(),
  add column if not exists updated_at      timestamptz not null default now(),
  add column if not exists deleted_at      timestamptz;

drop trigger if exists income_set_updated_at on public.income_entries;
create trigger income_set_updated_at
  before update on public.income_entries
  for each row execute function public.set_updated_at();

create index if not exists income_user_period_idx
  on public.income_entries (user_id, period)
  where deleted_at is null;


-- =============================================================================
-- expense_entries — the same shape as income, minus the "received on" date
-- =============================================================================
create table if not exists public.expense_entries (
  id      uuid primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  period  date not null
);

alter table public.expense_entries
  add column if not exists name        text not null default '',
  add column if not exists due_date    date,
  add column if not exists amount_due  numeric(14, 2) not null default 0,
  add column if not exists amount_paid numeric(14, 2) not null default 0,
  add column if not exists paid_date   date,
  add column if not exists category    text,
  add column if not exists notes       text,
  add column if not exists sort_order  integer not null default 0,
  add column if not exists created_at  timestamptz not null default now(),
  add column if not exists updated_at  timestamptz not null default now(),
  add column if not exists deleted_at  timestamptz;

drop trigger if exists expense_set_updated_at on public.expense_entries;
create trigger expense_set_updated_at
  before update on public.expense_entries
  for each row execute function public.set_updated_at();

create index if not exists expense_user_period_idx
  on public.expense_entries (user_id, period)
  where deleted_at is null;


-- =============================================================================
-- Row Level Security
--
-- This is what makes it safe for the app's key to sit in a public web page:
-- every row is locked to the account that owns it. Dropping and recreating a
-- policy only changes a rule, never any data.
-- =============================================================================
alter table public.profiles        enable row level security;
alter table public.income_entries  enable row level security;
alter table public.expense_entries enable row level security;

drop policy if exists "own profile: select" on public.profiles;
create policy "own profile: select" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "own profile: insert" on public.profiles;
create policy "own profile: insert" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "own profile: update" on public.profiles;
create policy "own profile: update" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "own income: select" on public.income_entries;
create policy "own income: select" on public.income_entries
  for select using (auth.uid() = user_id);

drop policy if exists "own income: insert" on public.income_entries;
create policy "own income: insert" on public.income_entries
  for insert with check (auth.uid() = user_id);

drop policy if exists "own income: update" on public.income_entries;
create policy "own income: update" on public.income_entries
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own income: delete" on public.income_entries;
create policy "own income: delete" on public.income_entries
  for delete using (auth.uid() = user_id);

drop policy if exists "own expenses: select" on public.expense_entries;
create policy "own expenses: select" on public.expense_entries
  for select using (auth.uid() = user_id);

drop policy if exists "own expenses: insert" on public.expense_entries;
create policy "own expenses: insert" on public.expense_entries
  for insert with check (auth.uid() = user_id);

drop policy if exists "own expenses: update" on public.expense_entries;
create policy "own expenses: update" on public.expense_entries
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own expenses: delete" on public.expense_entries;
create policy "own expenses: delete" on public.expense_entries
  for delete using (auth.uid() = user_id);


-- =============================================================================
-- Give every new account a profile row automatically
-- =============================================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- =============================================================================
-- The only thing in this project that deletes anything.
--
-- Defining the function does nothing on its own. It runs only when you type
-- DELETE into Settings → Data → Danger zone and press the button.
-- =============================================================================
create or replace function public.delete_all_my_data()
returns void
language plpgsql
security invoker
as $$
begin
  delete from public.income_entries  where user_id = auth.uid();
  delete from public.expense_entries where user_id = auth.uid();
end;
$$;
